config/routes.rb
Rails.application.routes.draw do
  


  root 'static_pages#home'
  
  
  get  '/help',    to: 'static_pages#help'
  get  '/about',   to: 'static_pages#about'
  get  '/contact', to: 'static_pages#contact'
  
  get '/signup', to: 'users#new'
  get 'users/new'
  
  get 'sessions/new'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  
  resources :users
  resources :tasks
  resources :projects
  
  
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def help
  end

  def contact
  end

  def about
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About") %>
<h1>The Chosen Ones</h1>
<p>The Chosen One's Capstone project</p>

app/views/static_pages/contact.html.erb
<% provide(:title, "Contact") %>
<h1>Contact Us</h1>
<p><i>We would love to know what you think about our project.</i></p>

app/views/static_pages/home.html.erb
<div class="center">
   <h1>Welcome to <br><span id="title">"THE CHOSEN ONES"</span><br>task application<h1>

      <% if logged_in? %>
       <%= link_to "New Task!",   new_task_path,    class: "btn btn-lg btn-primary" %>
       <%= link_to "New Project", new_project_path,           class: "btn btn-lg btn-primary" %>
      <% else %>
       <%= link_to "Sign up now!", new_user_path,  class: "btn btn-lg btn-primary" %>
      <% end %>
</div>